version: '3.8'

services:
  # Main Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
    container_name: deklaro-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env.production.local
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379
      - CLAMAV_HOST=clamav
      - CLAMAV_PORT=3310
    depends_on:
      - redis
      - clamav
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - deklaro-network
    volumes:
      - ./logs:/app/logs

  # Redis for Rate Limiting & Caching
  redis:
    image: redis:7-alpine
    container_name: deklaro-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-changeme}
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
      - deklaro-network

  # ClamAV for Virus Scanning
  clamav:
    image: clamav/clamav:latest
    container_name: deklaro-clamav
    restart: unless-stopped
    ports:
      - "3310:3310"
    volumes:
      - clamav-data:/var/lib/clamav
    healthcheck:
      test: ["CMD", "/usr/local/bin/clamdcheck.sh"]
      interval: 60s
      timeout: 30s
      retries: 3
      start_period: 300s
    networks:
      - deklaro-network

  # Nginx Reverse Proxy (Optional)
  nginx:
    image: nginx:alpine
    container_name: deklaro-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
      - nginx-cache:/var/cache/nginx
    depends_on:
      - app
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - deklaro-network

volumes:
  redis-data:
    driver: local
  clamav-data:
    driver: local
  nginx-cache:
    driver: local

networks:
  deklaro-network:
    driver: bridge
